env:
    #MANIFEST: https://github.com/PixelExperience/manifest.git -b eleven-plus
    DEVICE: p3s
    OEM: samsung
    DT_LINK: https://github.com/Nico17042020/android_device_samsung_p3s.git
    DT_PATH: device/$OEM/$DEVICE
    VT_LINK: https://github.com/Nico17042020/proprietary_vendor_samsung_p3s.git
    VT_PATH: vendor/$OEM/$DEVICE
    KT_LINK: https://github.com/Exy2100-LOS/android_kernel_samsung_universal2100.git
    PLATFORM: EWAF
    KT_PATH: kernel/$OEM/$PLATFORM
    TARGET: p3s
    EXTRA_CMD: 
    LUNCH_COMBO: lineage_${DEVICE}-userdebug
    OUTPUT: lineage*.zip

task:
  name: "Setting Up, Syncing, Building and Uploading..."
  timeout_in: 240m  
  container:
      image: ghcr.io/sushrut1101/docker:arch
      cpu: 4
      memory: 16G



  Storage-Checker_script:
      - df -h
      - lsblk
      - ls -l -a -h
  
  Sync_script:
      - echo "============================"
      - echo "Syncing The Sources..."
      - echo "============================"
      - mkdir -p ~/los
      - cd ~/los
      - repo init -u https://github.com/LineageOS/android.git -b lineage-20.0 --git-lfs --depth=1 
      - repo sync -j4 --force-sync --no-tags --no-clone-bundle
      - git clone $DT_LINK $DT_PATH
      - git clone $VT_LINK $VT_PATH
      - git clone $KT_LINK $KT_PATH
      - echo "============================"
      - echo "Syncing Complete!"
      - echo "============================"

  Build_script:
      - echo "============================"
      - echo "Starting the Build..."
      - echo "============================"
      - cd ~/los
      - $EXTRA_CMD
      - export USE_CCACHE=1
      - export CCACHE_EXEC=/usr/bin/ccache
      - ccache -M 50G
      - source build/envsetup.sh
      - breakfast p3s
      - croot
      - brunch p3s
     
  Upload_script:
      - echo "============================"
      - echo "Uploading the Build..."
      - echo "============================"
      - cd ~/los
      - cd out/target/product/"$DEVICE"
      - ls -lh
      - pwd
      - chmod 777 *
      - curl --upload-file $(echo $OUTPUT) https://transfer.sh | tee link.txt && echo " "
      - echo " "
      - echo "============================"
      - echo "Build Uploaded!"
      - echo "Please see the link Below-  "
      - echo "----------------------------"
      - cat link.txt && echo " "
      - echo "============================"
        

